import hashlib
import json
import time
import os

# --- Configuration ---
# Set the root directory you want to scan and generate provenance for
ROOT_DIRECTORY = "data_to_secure"
# The file where ALL provenance records will be stored
OUTPUT_MANIFEST_FILE = "directory_provenance_report.json"

# Placeholder for the 64-character hexadecimal hash generated by your QRNG/SHAKE256 script.
# This single Quantum Anchor secures the integrity of the entire report.
QUANTUM_RESISTANT_HASH_ROOT = "a1b2c3d4e5f67890a1b2c3d4e5f67890a1b2c3d4e5f67890a1b2c3d4e5f67890"


# --- 1. Helper Function: Calculate Standard File Hash (SHA256) ---
def calculate_file_hash(filepath, hash_algo=hashlib.sha256):
    """Calculates the SHA256 hash of a file's content."""
    hasher = hash_algo()
    try:
        with open(filepath, 'rb') as file:
            while True:
                chunk = file.read(4096)
                if not chunk:
                    break
                hasher.update(chunk)
        return hasher.hexdigest()
    except FileNotFoundError:
        return None
    except Exception as e:
        print(f"Error reading file {filepath}: {e}")
        return None

# --- 2. Core Function: Scan and Generate Provenance ---
def generate_directory_provenance(root_dir, qrng_hash_root):
    """
    Recursively scans a directory, hashes all files, and compiles an aggregated provenance manifest.
    """

    if not os.path.isdir(root_dir):
        print(f"Error: Directory '{root_dir}' not found. Please create it and add files.")
        return

    print(f"--- Starting Scan of Directory: {root_dir} ---")

    # Initialize the main report structure
    full_manifest = {
        "report_metadata": {
            "root_directory": os.path.abspath(root_dir),
            "timestamp": time.time(),
            "scan_description": "Batch Provenance Report for Quantum-Secured Assets",
            # The single, crucial Quantum Anchor for the entire report
            "quantum_anchor": {
                "alg": "SHAKE256 (PQC-Relevant)",
                "signature_root": qrng_hash_root,
            }
        },
        "file_records": []
    }

    file_count = 0

    # os.walk traverses the directory tree
    for root, _, files in os.walk(root_dir):
        for filename in files:
            full_path = os.path.join(root, filename)
            relative_path = os.path.relpath(full_path, root_dir)

            # Skip the manifest file if it's placed inside the root directory
            if filename == OUTPUT_MANIFEST_FILE:
                continue

            file_hash = calculate_file_hash(full_path)

            if file_hash:
                file_count += 1
                # Create a specific record for this file
                record = {
                    "filename": filename,
                    "relative_path": relative_path,
                    "size_bytes": os.path.getsize(full_path),
                    "assertions": [
                        {
                            "label": "stds.hash",
                            "data": {
                                "alg": "sha256",
                                "hash": file_hash
                            }
                        }
                    ]
                }
                full_manifest["file_records"].append(record)
                print(f" [✔] Hashed: {relative_path}")
            else:
                print(f" [!] Skipping: {relative_path} (Failed to read or hash)")

    print(f"\nScan complete. Total files processed: {file_count}")
    return full_manifest

# --- 3. Save the Manifest ---
def save_manifest(manifest_data, output_file):
    """Saves the completed provenance manifest to a JSON file."""
    try:
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(manifest_data, f, indent=4, ensure_ascii=False)
        print("-" * 70)
        print(f"✅ SUCCESSFULLY SAVED PROVENANCE REPORT to: {output_file}")
        print(f"Root Quantum Anchor (Partial): {manifest_data['report_metadata']['quantum_anchor']['signature_root'][:32]}...")
        print("-" * 70)
    except Exception as e:
        print(f"Error saving manifest: {e}")

# --- 4. Main Execution ---
if __name__ == "__main__":

    # --- DEMO SETUP: Create Dummy Data ---
    if not os.path.exists(ROOT_DIRECTORY):
        os.makedirs(os.path.join(ROOT_DIRECTORY, "subfolder_1"))
        os.makedirs(os.path.join(ROOT_DIRECTORY, "subfolder_2"))
        with open(os.path.join(ROOT_DIRECTORY, "real_photo.jpg"), 'w') as f:
            f.write("This is the original secure JPG data.")
        with open(os.path.join(ROOT_DIRECTORY, "subfolder_1", "document.pdf"), 'w') as f:
            f.write("A critical report.")
        print(f"\nNOTE: Created dummy directory structure and files in '{ROOT_DIRECTORY}'.")
    # -------------------------------------

    print("\n" + "=" * 70)
    print("STARTING BATCH QUANTUM-ANCHORED PROVENANCE GENERATION")
    print("=" * 70)

    # 1. Generate the manifest data
    manifest_data = generate_directory_provenance(ROOT_DIRECTORY, QUANTUM_RESISTANT_HASH_ROOT)

    # 2. Save the final report
    if manifest_data:
        save_manifest(manifest_data, OUTPUT_MANIFEST_FILE)